// <auto-generated />
using System;
using CombinationGeneratorAPI.Models.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CombinationGeneratorAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CombinationGeneratorAPI.Models.Entities.CombinationEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("RequestEntityId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RequestEntityId");

                    b.ToTable("Combinations");
                });

            modelBuilder.Entity("CombinationGeneratorAPI.Models.Entities.CombinationItemEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CombinationEntityId")
                        .HasColumnType("integer");

                    b.Property<string>("Item")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CombinationEntityId");

                    b.ToTable("CombinationItems");
                });

            modelBuilder.Entity("CombinationGeneratorAPI.Models.Entities.RequestEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("InputItems")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Requests");
                });

            modelBuilder.Entity("CombinationGeneratorAPI.Models.Entities.CombinationEntity", b =>
                {
                    b.HasOne("CombinationGeneratorAPI.Models.Entities.RequestEntity", "Request")
                        .WithMany("Combinations")
                        .HasForeignKey("RequestEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Request");
                });

            modelBuilder.Entity("CombinationGeneratorAPI.Models.Entities.CombinationItemEntity", b =>
                {
                    b.HasOne("CombinationGeneratorAPI.Models.Entities.CombinationEntity", "Combination")
                        .WithMany("Items")
                        .HasForeignKey("CombinationEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Combination");
                });

            modelBuilder.Entity("CombinationGeneratorAPI.Models.Entities.CombinationEntity", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("CombinationGeneratorAPI.Models.Entities.RequestEntity", b =>
                {
                    b.Navigation("Combinations");
                });
#pragma warning restore 612, 618
        }
    }
}
